### ISSUE TITLE
JSON changes without transition not listed as breaking

### ISSUE THREAD

**Issue by mbrancato** [protocolbuffers/protocolbuffers.github.io#152]
The JSON changes (specifically in Python, but possibly others) listed from `v25.3` -> `v.26` contain breaking changes but are not listed as such.

https://github.com/protocolbuffers/protocolbuffers.github.io/blob/08e0937a883848b800a8529a295997145604a772/content/news/v26.md?plain=1#L24-L25

This was not available in the immediately preceding version and will create runtime errors.

**Comment by Logofile** [comment]
Thanks for submitting this issue.

I think the reason you might not have seen it is that the breaking change was [mentioned](https://groups.google.com/g/protobuf/c/XKLsmdHbwPo) under "General Changes" rather than in "Python Breaking Changes": "[Python] Remove the deprecated always_print_primitive_fields option from Java, Python and C++ JSON parsers. (06e7cab)"
